export const app = "http://localhost:5000/api/";

export const tokenBasicUser: string =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlck5hbWUiOiJ0dWFuLnZ1dGhhbmgiLCJuYW1lIjoiVHXhuqVuIiwic3VybmFtZSI6IlbFqSBUaGFuaCIsInJvbGVOYW1lcyI6WyJCQVNJQ1VTRVIiLCJNQU5BR0VSIl0sImlzU3RvcFdvcmsiOmZhbHNlLCJpYXQiOjE2ODIzOTM2NjcsImV4cCI6MTY4Mjk5ODQ2N30.qT18qg_glYWCJiIhTTobxXOg6taBsEYdNMSIYEEBJ-Y";
export const tokenADMIN: string =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsIm5hbWUiOiJBRE1JTiIsInN1cm5hbWUiOiJTeXN0ZW0iLCJyb2xlTmFtZXMiOlsiQURNSU4iXSwiaXNTdG9wV29yayI6ZmFsc2UsImlhdCI6MTY4MjM4NzMzOCwiZXhwIjoxNjgyOTkyMTM4fQ.D71EjUbrdcfDWVgHPxxrGKVrGGECnvS8H5c7Qdb0OSg";
