name: deploy git
on: push
jobs:
  first-job:
    name: build nodejs
    runs-on: ubuntu:latest
    container: node:16.20.1
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm start
